// generated 2009/4/2 20:48:24 CLT by rvalenzu@rvalenzu-laptop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/rvalenzu/memoria/Aplicacion/TreeGrowthSimulator/AUV_selector.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in ./src/GUI_AUVSelector.hh and./src/GUI_AUVSelector.cc

#ifndef _GUI_AUVSELECTOR_GLADE_HH
#  define _GUI_AUVSELECTOR_GLADE_HH

// Since all your widgets were private I made them all public.
// To differentiate between accessable (e.g. entries, output labels)
// and unaccessible widgets (e.g. static labels, containers)
// you should use the 'visibility' property (only visible in C++ mode)


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA
#include <gtkmm/accelgroup.h>

class GlademmData
{

        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:

        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {
        }

        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>
#include <gtkmm/scale.h>
#include <gtkmm/paned.h>
#include <gtkmm/box.h>
#include "ScalesForParameters.h"

class GUI_AUVSelector_glade : public Gtk::Window
{
        GlademmData *gmm_data;
public:
        class Gtk::Window * GUI_AUVSelector;
protected:
        GUI_AUVSelector_glade();
        ~GUI_AUVSelector_glade();
        ScalesForParameters* things;
        virtual void on_hscale_value_changed(int i) = 0;
        virtual void on_cerrar_activate() = 0;

};
#endif
