// generated 2006/8/15 19:41:35 CLT by chupacabrasx@amd64-3000.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/chupacabrasx/Projects/modeladorCambiosGL/modeladorCambiosGL.glade
// for gtk 2.8.20 and gtkmm 2.8.8
//
// Please modify the corresponding derived classes in ./src/GUIDialogRefinar.hh and./src/GUIDialogRefinar.cc

#ifndef _GUIDIALOGREFINAR_GLADE_HH
#  define _GUIDIALOGREFINAR_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/spinbutton.h>

class GUIDialogRefinar_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * GUIDialogRefinar;
        class Gtk::Button * cancelbutton4;
        class Gtk::Button * okbutton4;
        class Gtk::RadioButton * radiobuttonLeppDelaunay;
        class Gtk::RadioButton * radiobuttonDelaunayLongestEdgeBisection;
        class Gtk::VBox * vbox3;
        class Gtk::Alignment * alignment4;
        class Gtk::Label * label20;
        class Gtk::Frame * frame4;
        class Gtk::RadioButton * radiobuttonAnguloMinimo;
        class Gtk::SpinButton * spinbuttonAnguloMinimo;
        class Gtk::HBox * hbox3;
        class Gtk::RadioButton * radiobuttonAreaCara;
        class Gtk::SpinButton * spinbuttonAreaCara;
        class Gtk::HBox * hbox4;
        class Gtk::RadioButton * radiobuttonLargoArcos;
        class Gtk::SpinButton * spinbuttonLargoArcos;
        class Gtk::HBox * hbox5;
        class Gtk::VBox * vbox5;
        class Gtk::Alignment * alignment5;
        class Gtk::Label * label21;
        class Gtk::Frame * frame5;
        class Gtk::VBox * vbox4;
protected:
        
        GUIDialogRefinar_glade();
        
        ~GUIDialogRefinar_glade();
private:
        virtual void on_radiobuttonAnguloMinimo_toggled() = 0;
        virtual void on_radiobuttonAreaCara_toggled() = 0;
        virtual void on_radiobuttonLargoArcos_toggled() = 0;
};
#endif
