// generated 2007/4/6 16:01:19 CLT by chupacabrasx@amd64-3000.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/chupacabrasx/codeblocks/TreeGrowthSimulator/modeladorCambiosGL.glade
// for gtk 2.10.6 and gtkmm 2.10.6
//
// Please modify the corresponding derived classes in ./src/GUIDialogDesrefinar.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
////#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "GUIDialogDesrefinar_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/adjustment.h>

GUIDialogDesrefinar_glade::GUIDialogDesrefinar_glade(
)
{  GUIDialogDesrefinar = this;
   gmm_data = new GlademmData(get_accel_group());
   cancelbutton5 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   okbutton5 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-apply")));

   Gtk::RadioButton::Group _RadioBGroup_radiobuttonAreaCara;
   radiobuttonAreaCara = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radiobuttonAreaCara, "Area Cara Minima"));

   Gtk::Adjustment *spinbuttonAreaCara_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 1000, 0.10000000149, 10, 10));
   spinbuttonAreaCara = Gtk::manage(new class Gtk::SpinButton(*spinbuttonAreaCara_adj, 1, 3));
   hbox7 = Gtk::manage(new class Gtk::HBox(false, 0));
   radiobuttonLargoArcos = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_radiobuttonAreaCara, "Largo Arcos Minimo"));

   Gtk::Adjustment *spinbuttonLargoArcos_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 1000, 0.10000000149, 10, 10));
   spinbuttonLargoArcos = Gtk::manage(new class Gtk::SpinButton(*spinbuttonLargoArcos_adj, 1, 3));
   hbox8 = Gtk::manage(new class Gtk::HBox(false, 0));
   vbox6 = Gtk::manage(new class Gtk::VBox(false, 0));
   alignment6 = Gtk::manage(new class Gtk::Alignment(0.5, 0.5, 1, 1));
   label23 = Gtk::manage(new class Gtk::Label("<b>Criterio</b>"));
   frame6 = Gtk::manage(new class Gtk::Frame());
   cancelbutton5->set_flags(Gtk::CAN_FOCUS);
   cancelbutton5->set_flags(Gtk::CAN_DEFAULT);
   cancelbutton5->set_relief(Gtk::RELIEF_NORMAL);
   okbutton5->set_flags(Gtk::CAN_FOCUS);
   okbutton5->set_flags(Gtk::CAN_DEFAULT);
   okbutton5->set_relief(Gtk::RELIEF_NORMAL);
   GUIDialogDesrefinar->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   radiobuttonAreaCara->set_flags(Gtk::CAN_FOCUS);
   radiobuttonAreaCara->set_relief(Gtk::RELIEF_NORMAL);
   radiobuttonAreaCara->set_mode(true);
   radiobuttonAreaCara->set_active(false);
   spinbuttonAreaCara->set_flags(Gtk::CAN_FOCUS);
   spinbuttonAreaCara->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbuttonAreaCara->set_numeric(true);
   spinbuttonAreaCara->set_digits(3);
   spinbuttonAreaCara->set_wrap(false);
   hbox7->pack_start(*radiobuttonAreaCara, Gtk::PACK_SHRINK, 0);
   hbox7->pack_start(*spinbuttonAreaCara);
   radiobuttonLargoArcos->set_flags(Gtk::CAN_FOCUS);
   radiobuttonLargoArcos->set_relief(Gtk::RELIEF_NORMAL);
   radiobuttonLargoArcos->set_mode(true);
   radiobuttonLargoArcos->set_active(false);
   spinbuttonLargoArcos->set_sensitive(false);
   spinbuttonLargoArcos->set_flags(Gtk::CAN_FOCUS);
   spinbuttonLargoArcos->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbuttonLargoArcos->set_numeric(true);
   spinbuttonLargoArcos->set_digits(3);
   spinbuttonLargoArcos->set_wrap(false);
   hbox8->pack_start(*radiobuttonLargoArcos, Gtk::PACK_SHRINK, 0);
   hbox8->pack_start(*spinbuttonLargoArcos);
   vbox6->pack_start(*hbox7, Gtk::PACK_SHRINK, 0);
   vbox6->pack_start(*hbox8, Gtk::PACK_SHRINK, 0);
   alignment6->add(*vbox6);
   label23->set_alignment(0.5,0.5);
   label23->set_padding(0,0);
   label23->set_justify(Gtk::JUSTIFY_LEFT);
   label23->set_line_wrap(false);
   label23->set_use_markup(true);
   label23->set_selectable(false);
   frame6->set_shadow_type(Gtk::SHADOW_NONE);
   frame6->set_label_align(0,0.5);
   frame6->add(*alignment6);
   frame6->set_label_widget(*label23);
   GUIDialogDesrefinar->get_vbox()->set_homogeneous(false);
   GUIDialogDesrefinar->get_vbox()->set_spacing(0);
   GUIDialogDesrefinar->get_vbox()->pack_start(*frame6);
   GUIDialogDesrefinar->set_title("Desrefinar");
   GUIDialogDesrefinar->set_modal(false);
   GUIDialogDesrefinar->property_window_position().set_value(Gtk::WIN_POS_NONE);
   GUIDialogDesrefinar->set_resizable(true);
   GUIDialogDesrefinar->property_destroy_with_parent().set_value(false);
   GUIDialogDesrefinar->set_has_separator(true);
   GUIDialogDesrefinar->add_action_widget(*cancelbutton5, -6);
   GUIDialogDesrefinar->add_action_widget(*okbutton5, -10);
   cancelbutton5->show();
   okbutton5->show();
   radiobuttonAreaCara->show();
   spinbuttonAreaCara->show();
   hbox7->show();
   radiobuttonLargoArcos->show();
   spinbuttonLargoArcos->show();
   hbox8->show();
   vbox6->show();
   alignment6->show();
   label23->show();
   frame6->show();
   GUIDialogDesrefinar->show();
   radiobuttonAreaCara->signal_toggled().connect(sigc::mem_fun(*this, &GUIDialogDesrefinar_glade::on_radiobuttonAreaCara_toggled), false);
   radiobuttonLargoArcos->signal_toggled().connect(sigc::mem_fun(*this, &GUIDialogDesrefinar_glade::on_radiobuttonLargoArcos_toggled), false);
}

GUIDialogDesrefinar_glade::~GUIDialogDesrefinar_glade()
{  delete gmm_data;
}
