// generated 2007/4/27 18:35:14 CLT by chupacabrasx@amd64-3000.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/chupacabrasx/codeblocks/TreeGrowthSimulator/TreeGrowthSimulator.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/GUIDialogDistribuirHormona.hh and./src/GUIDialogDistribuirHormona.cc

#ifndef _GUIDIALOGDISTRIBUIRHORMONA_GLADE_HH
#  define _GUIDIALOGDISTRIBUIRHORMONA_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/table.h>
#include <gtkmm/alignment.h>
#include <gtkmm/frame.h>
#include <gtkmm/box.h>

class GUIDialogDistribuirHormona_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * GUIDialogDistribuirHormona;
        class Gtk::Button * cancelbutton6;
        class Gtk::Button * okbutton6;
        class Gtk::Label * label47;
        class Gtk::Label * label48;
        class Gtk::Label * label49;
        class Gtk::SpinButton * spinbuttonGravitacional;
        class Gtk::SpinButton * spinbuttonLongitudinal;
        class Gtk::SpinButton * spinbuttonTangencial;
        class Gtk::Table * table9;
        class Gtk::Alignment * alignment11;
        class Gtk::Label * label46;
        class Gtk::Frame * frame11;
protected:
        
        GUIDialogDistribuirHormona_glade();
        
        ~GUIDialogDistribuirHormona_glade();
};
#endif
