// generated 2009/4/8 17:28:30 CLT by rvalenzu@rvalenzu-laptop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/rvalenzu/memoria/Aplicacion/TreeGrowthSimulator/projectinicio.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in ./src/GUIDialogInicio.hh and./src/GUIDialogInicio.cc

#ifndef _GUIDIALOGINICIO_GLADE_HH
#  define _GUIDIALOGINICIO_GLADE_HH

// Since all your widgets were private I made them all public.
// To differentiate between accessable (e.g. entries, output labels)
// and unaccessible widgets (e.g. static labels, containers)
// you should use the 'visibility' property (only visible in C++ mode)


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA
#include <gtkmm/accelgroup.h>

class GlademmData
{

        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:

        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {
        }

        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/button.h>
#include <gtkmm/box.h>

class GUIDialogInicio_glade : public Gtk::Window
{

        GlademmData *gmm_data;
public:
        class Gtk::Window * GUIDialogInicio;
        class Gtk::Button * button1;
        class Gtk::Button * button2;
        class Gtk::HBox * hbox1;
protected:

        GUIDialogInicio_glade();

        ~GUIDialogInicio_glade();
private:
        virtual void on_button1_clicked() = 0;
        virtual void on_button2_clicked() = 0;
};
#endif
