// generated 2007/4/6 16:01:19 CLT by chupacabrasx@amd64-3000.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/chupacabrasx/codeblocks/TreeGrowthSimulator/modeladorCambiosGL.glade
// for gtk 2.10.6 and gtkmm 2.10.6
//
// Please modify the corresponding derived classes in ./src/GUIDialogAbrirMatlab.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
////#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "GUIDialogAbrirMatlab_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/adjustment.h>

GUIDialogAbrirMatlab_glade::GUIDialogAbrirMatlab_glade(
)
{  GUIDialogAbrirMatlab = this;
   gmm_data = new GlademmData(get_accel_group());
   okbutton1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-ok")));

   Gtk::Adjustment *spinbuttonNumeroDeAnillos_adj = Gtk::manage(new class Gtk::Adjustment(0, 0, 1000, 1, 10, 10));
   spinbuttonNumeroDeAnillos = Gtk::manage(new class Gtk::SpinButton(*spinbuttonNumeroDeAnillos_adj, 1, 0));

   Gtk::Adjustment *spinbuttonPuntosPorAnillo_adj = Gtk::manage(new class Gtk::Adjustment(90, 0, 1000, 1, 10, 10));
   spinbuttonPuntosPorAnillo = Gtk::manage(new class Gtk::SpinButton(*spinbuttonPuntosPorAnillo_adj, 1, 0));
   label3 = Gtk::manage(new class Gtk::Label("Numero de anillos: "));
   label4 = Gtk::manage(new class Gtk::Label("Puntos por anillo:"));
   label5 = Gtk::manage(new class Gtk::Label("Tipo malla: "));
   comboTipoMalla = Gtk::manage(new class Gtk::Combo());
   table1 = Gtk::manage(new class Gtk::Table(2, 2, false));
   okbutton1->set_flags(Gtk::CAN_FOCUS);
   okbutton1->set_flags(Gtk::CAN_DEFAULT);
   okbutton1->set_relief(Gtk::RELIEF_NORMAL);
   GUIDialogAbrirMatlab->get_action_area()->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   spinbuttonNumeroDeAnillos->set_flags(Gtk::CAN_FOCUS);
   spinbuttonNumeroDeAnillos->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbuttonNumeroDeAnillos->set_numeric(true);
   spinbuttonNumeroDeAnillos->set_digits(0);
   spinbuttonNumeroDeAnillos->set_wrap(false);
   spinbuttonPuntosPorAnillo->set_flags(Gtk::CAN_FOCUS);
   spinbuttonPuntosPorAnillo->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbuttonPuntosPorAnillo->set_numeric(true);
   spinbuttonPuntosPorAnillo->set_digits(0);
   spinbuttonPuntosPorAnillo->set_wrap(false);
   label3->set_alignment(0,0.5);
   label3->set_padding(0,0);
   label3->set_justify(Gtk::JUSTIFY_LEFT);
   label3->set_line_wrap(false);
   label3->set_use_markup(false);
   label3->set_selectable(false);
   label4->set_alignment(0,0.5);
   label4->set_padding(0,0);
   label4->set_justify(Gtk::JUSTIFY_LEFT);
   label4->set_line_wrap(false);
   label4->set_use_markup(false);
   label4->set_selectable(false);
   label5->set_alignment(0,0.5);
   label5->set_padding(0,0);
   label5->set_justify(Gtk::JUSTIFY_LEFT);
   label5->set_line_wrap(false);
   label5->set_use_markup(false);
   label5->set_selectable(false);
   comboTipoMalla->get_entry()->set_flags(Gtk::CAN_FOCUS);
   comboTipoMalla->get_entry()->set_visibility(true);
   comboTipoMalla->get_entry()->set_editable(false);
   comboTipoMalla->get_entry()->set_max_length(0);
   comboTipoMalla->get_entry()->set_text("");
   comboTipoMalla->get_entry()->set_has_frame(true);
   comboTipoMalla->get_entry()->set_activates_default(false);
   comboTipoMalla->set_case_sensitive(false);
   {

      const char * const items[] = { "Triangulos", "Cuadrilateros", 0 };
      comboTipoMalla->set_popdown_strings(items);
   }
   comboTipoMalla->get_entry()->set_text("");
   table1->set_row_spacings(0);
   table1->set_col_spacings(0);
   table1->attach(*spinbuttonNumeroDeAnillos, 1, 2, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*spinbuttonPuntosPorAnillo, 1, 2, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label3, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label4, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*label5, 2, 3, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table1->attach(*comboTipoMalla, 2, 3, 1, 2, Gtk::EXPAND|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   GUIDialogAbrirMatlab->get_vbox()->set_homogeneous(false);
   GUIDialogAbrirMatlab->get_vbox()->set_spacing(0);
   GUIDialogAbrirMatlab->get_vbox()->pack_start(*table1);
   GUIDialogAbrirMatlab->set_title("Abrir Matlab");
   GUIDialogAbrirMatlab->set_modal(false);
   GUIDialogAbrirMatlab->property_window_position().set_value(Gtk::WIN_POS_NONE);
   GUIDialogAbrirMatlab->set_resizable(true);
   GUIDialogAbrirMatlab->property_destroy_with_parent().set_value(false);
   GUIDialogAbrirMatlab->set_has_separator(true);
   GUIDialogAbrirMatlab->add_action_widget(*okbutton1, -5);
   okbutton1->show();
   spinbuttonNumeroDeAnillos->show();
   spinbuttonPuntosPorAnillo->show();
   label3->show();
   label4->show();
   label5->show();
   comboTipoMalla->show();
   table1->show();
   GUIDialogAbrirMatlab->show();
}

GUIDialogAbrirMatlab_glade::~GUIDialogAbrirMatlab_glade()
{  delete gmm_data;
}
