// generated 2006/10/2 19:59:29 CLT by chupacabrasx@amd64-3000.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/chupacabrasx/Projects/modeladorCambiosGL/modeladorCambiosGL.glade
// for gtk 2.8.20 and gtkmm 2.8.8
//
// Please modify the corresponding derived classes in ./src/GUIDialogDesrefinar.hh and./src/GUIDialogDesrefinar.cc

#ifndef _GUIDIALOGDESREFINAR_GLADE_HH
#  define _GUIDIALOGDESREFINAR_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>

class GUIDialogDesrefinar_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * GUIDialogDesrefinar;
        class Gtk::Button * cancelbutton5;
        class Gtk::Button * okbutton5;
        class Gtk::RadioButton * radiobuttonAreaCara;
        class Gtk::SpinButton * spinbuttonAreaCara;
        class Gtk::HBox * hbox7;
        class Gtk::RadioButton * radiobuttonLargoArcos;
        class Gtk::SpinButton * spinbuttonLargoArcos;
        class Gtk::HBox * hbox8;
        class Gtk::VBox * vbox6;
        class Gtk::Alignment * alignment6;
        class Gtk::Label * label23;
        class Gtk::Frame * frame6;
protected:
        
        GUIDialogDesrefinar_glade();
        
        ~GUIDialogDesrefinar_glade();
private:
        virtual void on_radiobuttonAreaCara_toggled() = 0;
        virtual void on_radiobuttonLargoArcos_toggled() = 0;
};
#endif
