// generated 2009/4/8 17:28:30 CLT by rvalenzu@rvalenzu-laptop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/rvalenzu/memoria/Aplicacion/TreeGrowthSimulator/projectinicio.glade
// for gtk 2.12.9 and gtkmm 2.12.5
//
// Please modify the corresponding derived classes in ./src/GUIDialogInicio.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
////#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "GUIDialogInicio_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

GUIDialogInicio_glade::GUIDialogInicio_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  GUIDialogInicio = this;
   gmm_data = new GlademmData(get_accel_group());
   button1 = Gtk::manage(new class Gtk::Button(("TreeGrowthSimulator")));
   button2 = Gtk::manage(new class Gtk::Button(("FaceAnimationSimulator")));
   hbox1 = Gtk::manage(new class Gtk::HBox(false, 0));
   button1->set_flags(Gtk::CAN_FOCUS);
   button1->set_relief(Gtk::RELIEF_NORMAL);
   button2->set_flags(Gtk::CAN_FOCUS);
   button2->set_relief(Gtk::RELIEF_NORMAL);
   hbox1->pack_start(*button1, Gtk::PACK_SHRINK, 0);
   hbox1->pack_start(*button2, Gtk::PACK_SHRINK, 0);
   GUIDialogInicio->set_title(("Inicio Aplicación"));
   GUIDialogInicio->set_modal(false);
   GUIDialogInicio->property_window_position().set_value(Gtk::WIN_POS_CENTER);
   GUIDialogInicio->set_resizable(false);
   GUIDialogInicio->property_destroy_with_parent().set_value(false);
   GUIDialogInicio->add(*hbox1);
   button1->show();
   button2->show();
   hbox1->show();
   GUIDialogInicio->show();
   button1->signal_clicked().connect(sigc::mem_fun(*this, &GUIDialogInicio_glade::on_button1_clicked), false);
   button2->signal_clicked().connect(sigc::mem_fun(*this, &GUIDialogInicio_glade::on_button2_clicked), false);
}

GUIDialogInicio_glade::~GUIDialogInicio_glade()
{  delete gmm_data;
}
